export const glossary = [
  ['CRM','Customer relationship management: keeping useful customer details and history together.','The team can see Maya’s question and the next planned step.','what-is-crm'],
  ['Object','A type of thing recorded in the CRM.','Contact and Deal are different object types.','what-is-crm'],
  ['Record','One instance of an object.','Maya Patel is one contact record.','first-contact'],
  ['Contact','A person saved in the CRM.','Maya asks about a workshop.','first-contact'],
  ['Company','A business or organization recorded separately from its people.','Cedar Studio can have several associated contacts.','associations'],
  ['Deal','One defined possible sale, with its own stage and details.','Cedar Studio considers buying a team workshop.','deals-pipeline'],
  ['Ticket','A record of a support issue or request.','Maya cannot find the joining instructions.','tickets'],
  ['Property','A named field that stores a particular detail.','City stores London on a contact.','properties'],
  ['Property value','The information stored in a field on one record.','Design is the value of Workshop interest.','properties'],
  ['Internal name','The technical identifier for a property, distinct from its visible label.','An integration uses the field identifier rather than guessing from the label.','api-basics'],
  ['Association','A link between separate related records.','Maya is connected to Cedar Studio.','associations'],
  ['Owner','The teammate responsible for a record or process.','Jordan owns the next follow-up.','handoff'],
  ['Activity','An interaction or action recorded in the customer history.','A note explains what Maya asked during a call.','first-contact'],
  ['Lifecycle stage','A contact or company’s place in the overall marketing and sales relationship.','A qualified person may move from Lead to MQL under agreed rules.','lifecycle-stages'],
  ['MQL','Marketing qualified lead: marketing considers the person ready for sales under an agreed definition.','A relevant team-training request meets BrightPath’s example rule.','qualification'],
  ['SQL','Sales qualified lead: sales considers the person a potential customer.','A salesperson confirms a suitable training need.','lifecycle-stages'],
  ['Lead Status','A field for more detailed sales follow-up status, distinct from deal stage.','Attempted to Contact describes follow-up progress.','lifecycle-stages'],
  ['Pipeline','A set of stages used to track a process.','A sample deal moves from Qualified to Proposal to a decision.','deals-pipeline'],
  ['Deal stage','The current step for one sales opportunity.','Proposal describes a particular deal, not every relationship with that person.','deals-pipeline'],
  ['Closed won','A deal outcome indicating the sale was won under the team’s definition.','An accepted team workshop is recorded as won; payment is still a separate fact.','deals-pipeline'],
  ['Open pipeline','Opportunities not yet marked as won or lost under the report’s rules.','A pending proposal contributes to open value, not won value.','deals-pipeline'],
  ['Segment (formerly list)','A selected group of records.','People interested in Design form an audience group.','active-static'],
  ['Active segment','A group whose membership updates as records meet or stop meeting its rules.','A changed interest can move a contact out of the Design group.','active-static'],
  ['Static segment','A saved group that does not automatically re-evaluate its original rules.','A reviewed event-attendance snapshot stays fixed unless deliberately changed.','active-static'],
  ['Filter','A condition used to include or exclude records.','City equals London.','and-or'],
  ['AND','Logic requiring every connected condition to be true.','Design AND London requires both.','and-or'],
  ['OR','Logic requiring at least one connected condition to be true.','Design OR London can include people meeting either condition.','and-or'],
  ['Suppression','A reason a record is excluded from an action or audience.','An unsubscribed person must not receive the relevant marketing message.','audience-safety'],
  ['Marketing contact','A product classification used for marketing tools and billing in eligible accounts.','Marketing status does not override a newsletter opt-out.','audience-safety'],
  ['Subscription type','A category of communication with its own preference.','Monthly workshop tips is different from another newsletter.','consent'],
  ['Consent','An appropriate, evidenced permission for a stated use where required.','A real choice for a newsletter is not created by importing an address.','consent'],
  ['Opt-out','A choice not to receive a communication type or marketing communication.','Maya unsubscribes from monthly tips.','consent'],
  ['Form','A set of fields a visitor fills in to share information.','The workshop form asks for necessary registration details.','first-form'],
  ['Landing page','A focused page built around a particular offer or action.','One workshop page explains the offer and registration step.','landing-page'],
  ['CTA','Call to action: a clear prompt for a next step.','Register interest tells the visitor what the button does.','landing-page'],
  ['Conversion','A defined action you want to measure.','A completed registration is a conversion; a page view alone is not that conversion.','customer-journey'],
  ['Personalization token','A supported placeholder that inserts a recipient’s property value.','The real email editor can insert a first name.','personalization'],
  ['Fallback','Readable replacement text when a needed value is missing.','Hello there still works without a first name.','personalization'],
  ['Preview text','Supporting text many inboxes display beside or below the subject.','A short workshop summary gives context before opening.','first-email'],
  ['Deliverability','The ability of appropriate messages to reach intended inboxes, influenced by many factors.','Good authentication alone does not guarantee inbox placement.','email-quality'],
  ['Bounce','A message could not be delivered; the reason matters.','A permanently invalid address is not fixed by changing the subject.','email-quality'],
  ['DKIM','An email-authentication method using a cryptographic signature.','A domain administrator follows the sending platform’s setup instructions.','email-quality'],
  ['SPF','A domain policy describing authorized sending servers for the relevant sending identity.','The administrator reviews the correct SPF configuration rather than inventing it.','email-quality'],
  ['DMARC','A domain policy and reporting framework involving aligned email authentication.','The domain team reviews handling of messages that fail policy.','email-quality'],
  ['Campaign','Coordinated assets and activity aimed at a defined outcome.','A page, form, and invitation support one workshop initiative.','campaign-plan'],
  ['UTM parameter','A URL label used to describe a marketing source or campaign.','utm_medium=email labels the channel, not a person.','tracking-links'],
  ['SEO','Search engine optimization: helping people and search engines understand useful content.','A descriptive heading explains the page’s topic without keyword stuffing.','content-channels'],
  ['Workflow','Configured automation that enrolls records and performs actions.','A registration can lead to a reviewed follow-up process.','workflow-basics'],
  ['Enrollment trigger','The rule or event deciding which records enter a workflow.','The selected form submission starts a contact-based process.','workflow-basics'],
  ['Branch','A decision that sends a record along one of different paths.','A required eligibility check either continues or stops the sample flow.','branches-delays'],
  ['Delay','A pause before a later workflow action.','A person’s preferences may change during a one-day wait.','branches-delays'],
  ['Re-enrollment','A completed record entering a workflow again under supported configured rules.','A later qualifying event may start another run.','test-workflow'],
  ['Sequence','Targeted timed personal follow-up emails and tasks with configured stopping behavior.','A requested proposal gets a considered sales follow-up.','sequences'],
  ['SLA','Service-level agreement: an agreed expectation for response or service.','The team agrees who responds to a request and within what working hours.','handoff'],
  ['CSAT','Customer satisfaction: feedback about an experience, using the defined survey scale.','Check HubSpot’s current rating definition rather than assuming five stars.','customer-feedback'],
  ['CES','Customer effort score: feedback on how easy an experience was.','A joining-support survey asks about effort.','customer-feedback'],
  ['NPS','Net promoter score: conventionally percentage of promoters minus percentage of detractors.','NPS is not simply an average of 0–10 responses.','customer-feedback'],
  ['Metric','A defined measurement with a population, period, and counting rule.','Count unique qualifying deals closed in September.','report-question'],
  ['Denominator','The base number used in a fraction or rate.','A registration rate needs a clearly defined base of visits or people.','report-question'],
  ['Dashboard','A collection of reports used to understand and act on a situation.','Three focused reports guide a weekly review.','dashboards'],
  ['Attribution','Assigning outcome credit to recorded interactions under a chosen model.','First-touch and last-touch can assign different credit to the same journey.','attribution'],
  ['Source of truth','The agreed authoritative source for a particular fact.','An approved registration system owns registration status.','data-sync'],
  ['Seat','A user access type assigned within the account’s product packaging.','A required Sales or Service seat is separate from a specific permission.','permissions'],
  ['Permission','An allowed action or data-access scope for a user.','A trainee edits a draft while a reviewer controls publishing.','permissions'],
  ['API','A documented interface for software to request data or perform allowed actions.','An approved server reads specific contact fields.','api-basics'],
  ['OAuth','An authorization protocol used by applications to obtain scoped access.','A multi-account app follows the documented installation authorization flow.','api-basics'],
  ['Scope','A defined API access capability requested by an app.','A read-only integration requests necessary reads, not unrelated writes.','api-basics'],
  ['Pagination','Splitting a large API result into smaller response pages.','The first page of contacts may not be the full result.','api-basics'],
  ['Sandbox','A specific test-environment capability, not another name for every free account.','This site’s labs are simulations, not official HubSpot sandbox accounts.','safe-account'],
  ['Rollback','A realistic recovery plan for a change.','Restoring a setting does not recall already delivered emails.','change-control'],
  ['Quote','A proposed set of commercial terms for a sale.','A workshop quote is not proof that payment was collected.','ai-revenue'],
  ['Invoice','A request for payment under the relevant commercial process.','An invoice can exist before money is received.','ai-revenue'],
].map(([term,meaning,example,lesson])=>({term,meaning,example,lesson}));

export const projectChecklist = [
  'I wrote the audience, useful offer, owner, timeframe, and primary outcome.',
  'I can explain contacts, companies, deals, tickets, and their associations.',
  'I completed the contact and mapping labs and chose a sensible identifier.',
  'I tested Design AND London with subscribed-only required, including a nonmatch.',
  'I drafted a clear page and short form with appropriate privacy review noted.',
  'I tested email personalization with both a name and a missing name.',
  'I reviewed content, links, audience, sender, timing, and required footer checks.',
  'I tested the workflow’s qualifying, unsubscribed, and non-registration cases.',
  'I defined a deal-stage decision without confusing a won deal with payment.',
  'I defined the reporting population, date, unit, and counting rule.',
  'I documented approvals, monitoring, and realistic recovery before any live use.',
  'I kept all shared artifacts fictional and did not send, publish, or expose secrets.',
];

export const studyPlan = [
  ['Meet the toolkit','Start slowly. Explain CRM to a friend in one sentence.',['what-is-crm','hubspot-hubs']],
  ['Follow the customer','Map Maya’s journey and choose a safe place to learn.',['customer-journey','safe-account']],
  ['Know where to go','Find the main tool groups and write your practice safety rule.',['navigation','practice-rules']],
  ['Meet your first contact','Save a fictional record, then explain why each field belongs there.',['first-contact','properties'],'contact'],
  ['Connect the records','Draw Maya, Cedar Studio, one deal, and a ticket. Check the relationships.',['associations']],
  ['Prepare before importing','Read the small practice file and state its identifier and purpose.',['prepare-import']],
  ['Give every column a home','Complete the mapping challenge. Do not upload to a live account.',['map-import','clean-records'],'import'],
  ['Understand lead progress','Separate relationship stages from deal stages.',['lifecycle-stages','qualification']],
  ['Practice a good handoff','Write an owner, reason, promise, and next action for Maya.',['handoff']],
  ['Choose your kind of group','Compare an active audience with a saved snapshot.',['active-static'],'segments'],
  ['Make filters make sense','Try AND and OR, then inspect both matches and nonmatches.',['and-or','audience-safety'],'segments'],
  ['Design a useful form','Sketch a small form and explain where every answer goes.',['first-form']],
  ['Build the page around it','Give the offer one clear next step. Separate registration and subscription choices.',['landing-page','consent']],
  ['Draft a helpful email','Write one purpose, one useful message, and one main action.',['first-email']],
  ['Handle the missing name','Test a normal greeting and a fallback, then review the checklist.',['personalization','email-quality'],'email'],
  ['Connect the campaign','Write your one-page brief and channel plan. Keep everything in draft.',['campaign-plan','content-channels']],
  ['Label the visit source','Read a UTM example. Check that it contains no personal information.',['tracking-links']],
  ['Think before automating','Write when this happens, do that. Test one simple local run.',['workflow-basics'],'workflow'],
  ['Test more than the happy path','Compare eligible, unsubscribed, and non-registering cases.',['branches-delays','test-workflow'],'workflow'],
  ['Track an actual opportunity','Move a deal and compare open value with won value.',['deals-pipeline','tasks-meetings'],'pipeline'],
  ['Choose the right follow-up tool','Explain a sequence versus a workflow. Draft a support ticket.',['sequences','tickets']],
  ['Help people help themselves','Write a short support article and a useful feedback question.',['knowledge-base','customer-feedback']],
  ['Ask better reporting questions','Define one metric before choosing a chart.',['report-question','dashboards']],
  ['Read attribution carefully','Compare two simple credit models and list missing evidence.',['attribution']],
  ['Plan sensible access and sync','Write a scoped access request and a field-ownership mapping.',['permissions','data-sync']],
  ['Prepare a controlled change','List dependencies and test a model with more than one related record.',['change-control','custom-model']],
  ['Know the advanced boundaries','Learn API concepts and review an AI prompt. Do not enter credentials or make payments.',['api-basics','ai-revenue']],
  ['Build your end-to-end project','Assemble the fictional campaign brief, draft assets, and tested lab outcomes. Take extra time if needed.',['launch-project']],
  ['Review and troubleshoot','Use the project checklist and explain one surprising result with evidence.',['troubleshooting']],
  ['Celebrate, then choose what is next','Write an honest skills summary, export your progress, and choose an official Academy course.',['next-steps']],
].map(([title,task,lessons,lab])=>({title,task,lessons,lab}));