export const reviewed = '2026-09-29';

// Original explanations reference official documentation; no Academy course text is reproduced.
export const sources = {
  academy: { title: 'HubSpot Academy course catalog', url: 'https://academy.hubspot.com/courses', category: 'Official learning', review: 'Page reviewed' },
  certification: { title: 'Marketing Hub Software certification requirements', url: 'https://academy.hubspot.com/courses/hubspot-marketing-hub-software', category: 'Official learning', review: 'Official search excerpt reviewed' },
  catalog: { title: 'HubSpot Product and Services Catalog', url: 'https://legal.hubspot.com/hubspot-product-and-services-catalog', category: 'Plans and access', review: 'Relevant catalog sections reviewed; check live terms' },
  products: { title: 'HubSpot products and Smart CRM', url: 'https://www.hubspot.com/products', category: 'Foundations', review: 'Official search excerpt reviewed' },
  setup: { title: 'Set up your HubSpot account', url: 'https://knowledge.hubspot.com/get-started/set-up-your-account', category: 'Foundations', review: 'Official search excerpt reviewed' },
  security: { title: 'Set up two-factor authentication', url: 'https://knowledge.hubspot.com/account-security/set-up-two-factor-authentication-for-your-hubspot-login', category: 'Foundations', review: 'Official search excerpt reviewed' },
  objects: { title: 'Understand CRM objects', url: 'https://knowledge.hubspot.com/records/understand-objects', category: 'CRM and data', review: 'Official search excerpt reviewed' },
  records: { title: 'Create records on the index page', url: 'https://knowledge.hubspot.com/records/create-records-on-the-updated-index-page', category: 'CRM and data', review: 'Page reviewed' },
  properties: { title: 'Create and edit properties', url: 'https://knowledge.hubspot.com/properties/create-and-edit-properties', category: 'CRM and data', review: 'Page reviewed' },
  associations: { title: 'Associate records', url: 'https://knowledge.hubspot.com/records/associate-records', category: 'CRM and data', review: 'Official search excerpt reviewed' },
  imports: { title: 'Import records for a single object', url: 'https://knowledge.hubspot.com/import-and-export/import-records-for-a-single-object', category: 'CRM and data', review: 'Page reviewed' },
  duplicates: { title: 'Deduplicate records in HubSpot', url: 'https://knowledge.hubspot.com/records/deduplication-of-records', category: 'CRM and data', review: 'Official search excerpt reviewed' },
  lifecycle: { title: 'Use contact and company lifecycle stages', url: 'https://knowledge.hubspot.com/records/use-lifecycle-stages', category: 'CRM and data', review: 'Page reviewed' },
  segments: { title: 'Create active and static segments', url: 'https://knowledge.hubspot.com/segments/create-active-or-static-lists', category: 'Marketing', review: 'Page reviewed' },
  marketingContacts: { title: 'Understand marketing contacts', url: 'https://knowledge.hubspot.com/records/marketing-contacts', category: 'Marketing', review: 'Official search excerpt reviewed' },
  forms: { title: 'Create and customize forms', url: 'https://knowledge.hubspot.com/forms/create-and-edit-forms', category: 'Marketing', review: 'Page reviewed' },
  pages: { title: 'Create and customize pages', url: 'https://knowledge.hubspot.com/website-and-landing-pages/create-and-customize-pages', category: 'Marketing', review: 'Page excerpts reviewed' },
  email: { title: 'Create and send marketing emails', url: 'https://knowledge.hubspot.com/marketing-email/create-and-send-marketing-emails', category: 'Marketing', review: 'Page reviewed' },
  subscriptions: { title: 'Set up email subscription types', url: 'https://knowledge.hubspot.com/marketing-email/set-up-email-subscription-types', category: 'Marketing', review: 'Official search excerpt reviewed' },
  authentication: { title: 'Overview of email authentication', url: 'https://knowledge.hubspot.com/marketing-email/overview-of-email-authentication', category: 'Marketing', review: 'Official search excerpt reviewed' },
  campaigns: { title: 'Create campaigns', url: 'https://knowledge.hubspot.com/campaigns/create-campaigns', category: 'Marketing', review: 'Page reviewed' },
  tracking: { title: 'Create tracking URLs', url: 'https://knowledge.hubspot.com/settings/how-do-i-create-a-tracking-url', category: 'Marketing', review: 'Official search excerpt reviewed' },
  social: { title: 'Create and publish social posts', url: 'https://knowledge.hubspot.com/social/create-and-publish-social-posts', category: 'Marketing', review: 'Official search excerpt reviewed' },
  ads: { title: 'Connect and set up ad accounts', url: 'https://knowledge.hubspot.com/ads/connect-and-set-up-your-ad-accounts-in-hubspot', category: 'Marketing', review: 'Official search excerpt reviewed' },
  workflows: { title: 'Create workflows', url: 'https://knowledge.hubspot.com/workflows/create-workflows', category: 'Automation', review: 'Page reviewed' },
  pipelines: { title: 'Set up and manage object pipelines', url: 'https://knowledge.hubspot.com/object-settings/set-up-and-customize-pipelines', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  sequences: { title: 'Create and edit sequences', url: 'https://knowledge.hubspot.com/sequences/create-and-edit-sequences', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  meetings: { title: 'Create scheduling pages with the meetings tool', url: 'https://knowledge.hubspot.com/meetings-tool/create-and-edit-scheduling-pages', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  helpdesk: { title: 'Set up help desk', url: 'https://knowledge.hubspot.com/help-desk/overview-of-the-help-desk-workspace', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  knowledge: { title: 'Create and customize knowledge base articles', url: 'https://knowledge.hubspot.com/knowledge-base/create-and-customize-knowledge-base-articles', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  feedback: { title: 'HubSpot survey response properties', url: 'https://knowledge.hubspot.com/customer-feedback/survey-response-properties', category: 'Sales and service', review: 'Official search excerpt reviewed' },
  reports: { title: 'Create custom reports', url: 'https://knowledge.hubspot.com/reports/create-custom-reports', category: 'Reporting', review: 'Page reviewed' },
  emailMetrics: { title: 'Analyze marketing email performance', url: 'https://knowledge.hubspot.com/marketing-email/analyze-your-marketing-email-campaign-performance', category: 'Reporting', review: 'Official search excerpt reviewed' },
  attribution: { title: 'Understand attribution reporting', url: 'https://knowledge.hubspot.com/reports/understand-attribution-reporting', category: 'Reporting', review: 'Official search excerpt reviewed' },
  permissions: { title: 'HubSpot user permissions guide', url: 'https://knowledge.hubspot.com/user-management/hubspot-user-permissions-guide', category: 'Administration', review: 'Official search excerpt reviewed' },
  sync: { title: 'Connect and use HubSpot data sync', url: 'https://knowledge.hubspot.com/integrations/connect-and-use-hubspot-data-sync', category: 'Administration', review: 'Official search excerpt reviewed' },
  model: { title: 'Use the data model builder', url: 'https://knowledge.hubspot.com/data-management/use-the-data-model-builder', category: 'Administration', review: 'Official search excerpt reviewed' },
  api: { title: 'Developer platform authentication overview', url: 'https://developers.hubspot.com/docs/apps/developer-platform/build-apps/authentication/overview', category: 'Advanced', review: 'Official search excerpt reviewed' },
  limits: { title: 'API usage guidelines and limits', url: 'https://developers.hubspot.com/docs/developer-tooling/platform/usage-guidelines', category: 'Advanced', review: 'Official search excerpt reviewed' },
  breeze: { title: 'Use Breeze Assistant', url: 'https://knowledge.hubspot.com/ai/use-breeze-assistant', category: 'Advanced', review: 'Official search excerpt reviewed' },
};

for (const source of Object.values(sources)) source.checked = reviewed;